// EXRDemux JSX helpers
//
// Drop-in functions for automation scripts (typically generated by the
// upstream Blender addon) that need to drive an EXRDemux effect by
// layer NAME instead of slot index. The hash function must match the
// HashLayerName() in src/exrdemux.cpp byte-for-byte — if you change one,
// change the other.
//
// Usage:
//   //@include "exrdemux_helpers.jsx"   // or paste into your script
//   exrdemuxSetLayer(myEffect, "CurtainUplight_001");

(function (exports) {

    // 32-bit unsigned multiplication, splitting into 16-bit halves to
    // stay within JS double precision. ExtendScript predates Math.imul.
    function imul32(a, b) {
        var aLo = a & 0xFFFF;
        var aHi = (a >>> 16) & 0xFFFF;
        var bLo = b & 0xFFFF;
        var bHi = (b >>> 16) & 0xFFFF;
        var lo = aLo * bLo;
        var mid = ((aHi * bLo) + (aLo * bHi)) << 16;
        return (lo + (mid >>> 0)) >>> 0;
    }

    // FNV-1a 32-bit. MUST match HashLayerName() in exrdemux.cpp.
    function exrdemuxHashLayerName(name) {
        var h = 2166136261;
        for (var i = 0; i < name.length; i++) {
            h ^= name.charCodeAt(i) & 0xFF;
            h = imul32(h, 16777619);
        }
        return h;
    }

    // Set the EXRDemux effect's layer selection by NAME. Survives EXR
    // re-renders that shift channel ordering, because the plugin
    // resolves the hash against the current EXR at render time.
    //
    // The hash is split across two 16-bit halves because AE's float32
    // persistence path corrupts integers above ~16M when stored in a
    // single PF_Param_FLOAT_SLIDER.
    function exrdemuxSetLayer(effect, layerName) {
        var hash = exrdemuxHashLayerName(layerName);
        var hi = (hash >>> 16) & 0xFFFF;
        var lo = hash & 0xFFFF;
        effect.property("Layer Hash Hi").setValue(hi);
        effect.property("Layer Hash Lo").setValue(lo);
    }

    // Set by current popup slot index (1-based). Faster than hashing
    // when the caller already knows the EXR's channel order, but does
    // NOT survive re-renders with shifted channels — prefer setLayer
    // for anything you'd save into a project.
    function exrdemuxSetSlot(effect, slot) {
        effect.property("Layer").setValue(slot);
    }

    exports.exrdemuxHashLayerName = exrdemuxHashLayerName;
    exports.exrdemuxSetLayer      = exrdemuxSetLayer;
    exports.exrdemuxSetSlot       = exrdemuxSetSlot;

})($.global);
